### ISSUE TITLE
Autocomplete list cannot open link

### ISSUE THREAD

**Issue by frydo** [swiftype/swiftype-autocomplete-jquery#28]
Hello,

i have this custom function with a link. 
`var customRenderFunction = function(document_type, item) {
		return '<a class="acLink" href="' + item['deeplink'] + '"><span class="title"><img src="' + item['d_thumb_image'] + '" />' + item['gername'] + '</span></a>';
	};`

But when i open one of the links from ac list i get redirected to a 404 page.
I have activated "preserve log" in chrome dev tools -> network. 
What happen is. The link get "canceled" -> then an 302 and on the end an 404. Don't know why.
When i open the link by pressing right mouse -> open all works fine.

**Comment by frydo** [comment]
I get this error in chrome dev tools

`Uncaught TypeError: jQuery111102709781619156051_1527109516708 is not a function
    at VM3387 suggest.json:1
(anonymous) @ VM3387 suggest.json:1
`

**Comment by JasonStoltz** [comment]
Hey @frydo, sorry for the late reply.

This issue is that the `onComplete` handler is being executed when your link is clicked.

https://github.com/swiftype/swiftype-autocomplete-jquery/blob/master/jquery.swiftype.autocomplete.js#L409

This is canceling the original link navigation that you created, which navigates a user to the `deepLink` property, and instead, routing the user to the `url` property.

The fix for this is simple, just provide a no-op `onComplete` implementation to override the default behavior when initializing your autocomplete.

```
$('#st-search-input').swiftype({ 
	engineKey: 'jaDGyzkR6iYHkfNsPpNK',
	onComplete: function() { }
});
```
