### ISSUE TITLE
Need the Oncomplete function to store value in Input field instead of redirection

### ISSUE THREAD

**Issue by Janasidhu** [swiftype/swiftype-autocomplete-jquery#30]
I need a solution for swiftype onComplete function. On selecting the options from swiftype list, it redirects to the location of clicked option . instead i just want to show the clicked value in input field at the same time, the search query should store in swiftype dashboard for analytics.

I tried this method, but bit confuse how to do this.
I found the default function 
var defaultOnComplete = function(item, prefix) {
    window.location = item['url'];
  };

in swiftype search WordPress plugin inside the assets folder.

I have seen some replaceable code but that doesn't work with swiftype plugin. Any help would be thankful.

**Comment by JasonStoltz** [comment]
Hi @Janasidhu. In order to change what happens when clicking on a result item, you need to provide an `onComplete` implementation.

`onComplete` is provided when first initializing the autocomplete dropdown. Simply save a reference to the `input` element of the autocomplete dropdown after initializing it, then set it's `val` in `onComplete`.

Here is an example:

```javascript
var input; // Save a reference to the autocomplete dropdown
input = $('#st-search-input').swiftype({ 
	onComplete: function(selectedItem) {
          input.val(selectedItem['title']); // Update the autocomplete dropdown's value
        },
	fetchFields: {'books': ['title']},
	engineKey: 'jaDGyzkR6iYHkfNsPpNK'
});
```
