### ISSUE TITLE
Trouble fetching fields I specify

### ISSUE THREAD

**Issue by webinc** [swiftype/swiftype-autocomplete-jquery#42]
I am following the tutorial [here ](https://github.com/swiftype/swiftype-autocomplete-jquery#usage) to customise my results and show the fields I specify in the dropdown.

My engine is called AZTwo and I have tried with this code to specify the fields I want. These are the field names given them by SwiftType, as shown in my control panel:

```
var showQuickResults = function(document_type, item) {
	var out = '<p><a href="' + Swiftype.htmlEscape(item['url']) + '" class="st-search-result-link">' + item.highlight['title'] + '</a>';
	return out.concat('<span style="width: 20px">  -  <span class="object_type">' + item.highlight['object_type'] + '</span></span>');
};                            


jQuery('#st-search-input').swiftype({
  renderFunction: showQuickResults,
  engineKey: '{my_engine_key}',
  fetchFields : {'aztwo' : ['title', 'object_type', 'excerpt', 'external_id' ] },
  searchFields: { 'aztwo': ['title'] },
});
```
However, the results I get show 'undefined' instead of the object_type value.
(See attached screenshot).
Can you tell me what I'm doing wrong?

Many thanks
Tim
![swiftype](https://user-images.githubusercontent.com/5823627/66147374-a1304c00-e606-11e9-9016-22203e9252b0.jpg)

**Comment by yakhinvadim** [comment]
I think the problem might be that we're trying to access `item.highlight['object_type']` which resolves to undefined, because we don't have `object_type` in `highlightFields`.

The third code block in [this section](https://github.com/swiftype/swiftype-autocomplete-jquery#customizing-the-display) has an example of using `highlightFields`.

I see two possible solutions here:
1) Try setting up `highlightFields` when you initialize plugin
2) Instead of `item.highlight['object_type']` try accessing `item['object_type']`

Let us know if it worked!

**Comment by webinc** [comment]
Thank you. Yes - changing it to `item['object_type'] `  worked perfectly. 
I will read up on highlightFields as you suggest.

Many thanks for your speedy help. Much appreciated!
